### ISSUE TITLE
OperationalError: no such table: listener

### ISSUE THREAD

**Issue by leoandrews** [radiocicletta/morganfreeman#13]
Just trying out your work - it should be really cool.

Unfortunately whenever I start it, I get the error 

```
-- MARK --
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/home/ec2-user/morganfreeman/icestats/daemon.py", line 249, in run
    timedupdate()
  File "/home/ec2-user/morganfreeman/icestats/daemon.py", line 190, in timedupdate
    db = DB(self.db)
  File "/home/ec2-user/morganfreeman/icestats/db.py", line 51, in __init__
    self.db.execute(sql)
OperationalError: no such table: listener
```

What might be causing that?

**Comment by leofiore** [comment]
I suppose the database hasn't been initialized properly.

a few question to collect more context:

Where is the stats.sqlite file located? 
Have you checked if it is initialized properly? 
Have you checked if the database's path is accessible or the application has write permissions on it? 
Have you seen any other exception during the start of the application?

**Comment by leoandrews** [comment]
The stats.sqlite is in the 'morganfreeman' application directory

There's a few exceptions - here's what happens when you launch it

```
Traceback (most recent call last):
  File "frosty.py", line 5, in <module>
    from icestats import daemon
  File "/home/ec2-user/morganfreeman/icestats/daemon.py", line 7, in <module>
    from db import DB
  File "/home/ec2-user/morganfreeman/icestats/db.py", line 4, in <module>
    import maxminddb
ImportError: No module named maxminddb

```

**Comment by leofiore** [comment]
Looks to me not all of the dependencies modules are satasfied. Have you checked your python environment? The master branch requires python2.7 and all of the modules listed in the `requirements.txt` file. If you haven't installed it, you may want to follow the install instructions on the README.md to create a virtualenv and run it from there.

If you already had created the virtualenv and installed all of the required modules, you should check if the installation is successfully completed. Try to activate your virtualenv in a shell and type `pip freeze` to obtain the list of the installed modules. If `maxminddb` is not listed, then you know for sure something gone wrong.

If you are using python3 , then you may want to use the `py3` branch (it is not widely tested though it usually runs fine). the installation instructions are quite the same, except you'll have to use `pip3` .

Finally, if you are familiar with docker, you can try to build and run a container using the provided `Dockerfile`. 

Also, as a side note, i found out now that MaxMind GeoLite database is no more available via direct download. you may want to download the updated one via reading their [documentation](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en), otherwise, you can download an outdated version from https://github.com/texnikru/GeoLite2-Database

**Comment by leoandrews** [comment]
The `requirements.txt` file is a ten-byte file. Is that right?

Also if I do a pip freeze I get

```
ipaddress==1.0.23
maxminddb==1.5.4
```

**Comment by leofiore** [comment]
That is correct. The only requirement is the maxminddb module. If the module is correctly installed, there is no way  you can have the error `ImportError: No module named maxminddb`. The only reason that comes in my mind causing that is the fact that you have created a virtualenv but you are not running the application inside the virtualenv. 

I tried myself to repeat the installation procedure in a clean environment:

```bash
leonardo$ docker run -it --rm python:2.7 --network icecast_test bash
root@f95f0c14d120:/# date
Wed Dec  1 14:59:53 UTC 2021
root@f95f0c14d120:/# git clone https://github.com/radiocicletta/morganfreeman.git
Cloning into 'morganfreeman'...
remote: Enumerating objects: 246, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 246 (delta 0), reused 3 (delta 0), pack-reused 240
Receiving objects: 100% (246/246), 256.05 KiB | 2.17 MiB/s, done.
Resolving deltas: 100% (123/123), done.
root@f95f0c14d120:/# cd morganfreeman/
root@f95f0c14d120:/morganfreeman# pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting maxminddb
  Downloading maxminddb-1.5.4.tar.gz (282 kB)
     |████████████████████████████████| 282 kB 5.8 MB/s
Collecting ipaddress
  Downloading ipaddress-1.0.23-py2.py3-none-any.whl (18 kB)
Building wheels for collected packages: maxminddb
  Building wheel for maxminddb (setup.py) ... done
  Created wheel for maxminddb: filename=maxminddb-1.5.4-cp27-cp27mu-linux_x86_64.whl size=41452 sha256=10df649fc0860497557541521dfe87a64fa0034a013b546289b8631c0fa03111
  Stored in directory: /root/.cache/pip/wheels/a8/b5/b6/97962cef7dbae9d88e81bd2a5c2f34bc0163bd5ce391434a21
Successfully built maxminddb
Installing collected packages: ipaddress, maxminddb
Successfully installed ipaddress-1.0.23 maxminddb-1.5.4
WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@f95f0c14d120:/morganfreeman# wget https://github.com/texnikru/GeoLite2-Database/raw/master/GeoLite2-City.mmdb.gz
--2021-12-01 14:24:22--  https://github.com/texnikru/GeoLite2-Database/raw/master/GeoLite2-City.mmdb.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/texnikru/GeoLite2-Database/master/GeoLite2-City.mmdb.gz [following]
--2021-12-01 14:24:22--  https://raw.githubusercontent.com/texnikru/GeoLite2-Database/master/GeoLite2-City.mmdb.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24014525 (23M) [application/octet-stream]
Saving to: ‘GeoLite2-City.mmdb.gz’

GeoLite2-City.mmdb.gz       100%[=========================================>]  22.90M  18.7MB/s    in 1.2s

2021-12-01 14:24:26 (18.7 MB/s) - ‘GeoLite2-City.mmdb.gz’ saved [24014525/24014525]

root@f95f0c14d120:/morganfreeman# gunzip GeoLite2-City.mmdb.gz
root@f95f0c14d120:/morganfreeman# python frosty.py -h http://icecast:8000 -u admin -w test -b 9000 -r "Icecast2 Server"
-- MARK --
-- MARK --
-- MARK --
```

This is the whole procedure from start to finish running. I tried it right now and it successfully runs. The procedure using a virtualenv is quite the same, except that you have to install all of your deps in the activated virtualenv, and run the application inside the virtualenv. You may want to try and replicate the steps i used, starting from scratch (it may help to delete all of the files, included the `stats.sqlite` file). If you are trying to install and run the application in some other ways, please provide all of the steps you performed, and possibily attach a more usefult output from your terminal, the longer the better.

**Comment by leoandrews** [comment]
Followed the steps. There's good news and bad news. the good news is that the application runs without errors now. The bad news is that this looks a bit broken?
![image](https://user-images.githubusercontent.com/742000/144522898-0e1bd67c-8edb-4081-bcac-3667ab02d4e1.png)

Note that the 'current listeners' at the top is not populating and I'm not sure what the heat map is supposed to be showing but it's only been running 10 minutes, I'm not sure why it would show data going back 18 hours in the past

**Comment by leofiore** [comment]
The heatmap has visible quirks that should disappear after 24 hours of operativity. 

As you may have noticed, this project is not very active since 2015. If you look at the buglist opened for the interface you'd notice there is a lot of work to do. The graphic library was pretty much made from scratch, so there is a chance that some corner cases are still uncovered. Time zone is one of those (which is the reason the heatmap is struggling to show you the correct visualization), along with a real communication with the icecast server, or the use of a websocket for constant updates on the service (which is the reason you are not seeing any number in the "current listeners" field).

I was planning a major rewrite on the user interface, then life happened for me and the rest of the developers. We currently maintain the project by occasionally fixing the backend part, which is probably the most valuable part of the project since it could be used even without the web interface.

If you find this project useful or at least relevant, and you feel to contribute, feel free to inspect the list of the opened bugs, and if you find something missing, you can add more. If you are a developer, and you are willing to propose patches and improvements in the code, we'll be open to review and integrate it. Contributions are more than welcome.

As you can see, i closed the issue since it really wasn't a problem on the code. Please do not use this issue as a product support channel for solving all of the problems in the setup of your instance, since it is beyond the scope of a bugtracker.
